import type { Metadata } from "next";
import { Unbounded, Roboto } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ['400', '700']
});

const unbounded = Unbounded({
  variable: "--font-unbounded-mono",
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Abi Rahmawan",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" href="/logo.png" />
        {/* Optional: Tambahkan format lain jika diperlukan */}
        {/* <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" /> */}
      </head>
      <body
        style={{ fontFamily: 'var(--font-roboto)' }}
        className={`${robotoSans.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
